### ISSUE TITLE
Uncaught exception: TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function

### ISSUE THREAD

**Issue by niftylettuce** [keymetrics/pm2-logrotate#106]
```sh
0|pm2-logr | TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function
0|pm2-logr |     at _addListener (events.js:246:11)
0|pm2-logr |     at WriteStream.addListener (events.js:306:10)
0|pm2-logr |     at WriteStream.close (fs.js:2282:10)
0|pm2-logr |     at WriteStream.<anonymous> (/home/deploy/.pm2/node_modules/pm2-logrotate/app.js:138:17)
0|pm2-logr |     at emitNone (events.js:120:20)
0|pm2-logr |     at WriteStream.emit (events.js:218:7)
0|pm2-logr |     at finishMaybe (_stream_writable.js:605:14)
0|pm2-logr |     at endWritable (_stream_writable.js:613:3)
0|pm2-logr |     at WriteStream.Writable.end (_stream_writable.js:564:5)
0|pm2-logr |     at ReadStream.onend (_stream_readable.js:598:10)
PM2        | App [pm2-logrotate] with id [0] and pid [9217], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:pm2-logrotate id:0
PM2        | App name:pm2-logrotate id:0 online
```

**Comment by cuteboi** [comment]
```
2|pm2-logrotate  | TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function
2|pm2-logrotate  |     at _addListener (events.js:180:11)
2|pm2-logrotate  |     at WriteStream.addListener (events.js:240:10)
2|pm2-logrotate  |     at WriteStream.close (fs.js:2298:10)
2|pm2-logrotate  |     at WriteStream.<anonymous> (/root/.pm2/modules/pm2-logrotate/node_modules/pm2-logrotate/app.js:138:17)
2|pm2-logrotate  |     at WriteStream.emit (events.js:164:20)
2|pm2-logrotate  |     at finishMaybe (_stream_writable.js:616:14)
2|pm2-logrotate  |     at endWritable (_stream_writable.js:624:3)
2|pm2-logrotate  |     at WriteStream.Writable.end (_stream_writable.js:575:5)
2|pm2-logrotate  |     at ReadStream.onend (_stream_readable.js:598:10)
2|pm2-logrotate  |     at Object.onceWrapper (events.js:254:19)
```

Experiencing this on:
freebsd 10.3
pm2 version 3.0.3
pm2-logrotate 2.6.0
node v9.3.0
npm 5.6.0

**Comment by jniles** [comment]
Also experiencing this on node v9.11.2.  Could it be a regression of https://github.com/keymetrics/pm2-logrotate/issues/48?

**Comment by suburbanworrier** [comment]
Exact same error on:

* Ubuntu 16.04.5 LTS
* pm2 3.2.2
* pm2-logrotate 2.6.0
* node v9.3.0
* npm 5.5.1

**Comment by zhongzhong0505** [comment]
same problem

**Comment by korob93** [comment]
Any news?
