### ISSUE TITLE
"Error: <files> required" exception, and logs aren't rotating

### ISSUE THREAD

**Issue by matAtWork** [keymetrics/pm2-logrotate#156]
Any info on how to start tracking this down?

```
Error: <files> required
    at Object.<anonymous> (/home/rta/.pm2/modules/logrotate/node_modules/logrotate/bin/rotate:38:26)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Object.<anonymous> (/home/rta/.nvm/versions/node/v14.2.0/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
```

**Comment by pecliu** [comment]
Same error. the plugin didn't work

**Comment by ArunJRK** [comment]
> Same error after run `pm2 install logrotate`.
> 
> Try `pm2 uninstall logrotate` and then `pm2 install pm2-logrotate`

This worked thanks

**Comment by matAtWork** [comment]
Sadly I'm still seeing this, and uninstall/re-install made no difference

**Comment by matAtWork** [comment]
🤦  - it's `pm2-logrotate` not `logrotate`

All works fine now
