### ISSUE TITLE
No of restart of logrotate is too high

### ISSUE THREAD

**Issue by sas7085** [keymetrics/pm2-logrotate#94]
Hi 

The no of restart of logrotate is too high. Not sure this is issue with log rorate or this is the way logrotate used to work. 
Its only 7 days of installation of logrotate module .
![image](https://user-images.githubusercontent.com/36013435/36496730-3326be76-1707-11e8-9c3b-2d7f086f1ec9.png)

**Comment by HonzaMac** [comment]
Try `pm2 logs pm2-logrotate` and you will see, what is wrong.
Which node version are you using?

**Comment by unusualbob** [comment]
I have the same thing currently, running 4.x for an older application that hasn't been upgraded yet. The error I'm hitting looks to be use of .includes which wasn't supported until recent node versions.

```1|pm2-logr | TypeError: WATCHED_FILES.includes is not a function
1|pm2-logr |     at proceed_file (/xxxx/.pm2/node_modules/pm2-logrotate/app.js:159:22)
1|pm2-logr |     at null._repeat (/xxxx/.pm2/node_modules/pm2-logrotate/app.js:212:5)
1|pm2-logr |     at wrapper [as _onTimeout] (timers.js:279:11)
1|pm2-logr |     at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by HonzaMac** [comment]
Problem is, that you have newer version of logrotate, that does not support old node 4.x
Last working is `2.2.4`, downgrade.
`pm2 install pm2-logrotate@2.2.4` <- lock version during installation.
